"""Shared types and enums for Lancer TTRPG."""

from core.shared.enums import (
    ActionType,
    AttackType,
    CoverType,
    DamageType,
    RangeType,
    SizeClass,
    ManufacturerType,
    MountType,
    SystemType,
    StatusType,
)
from core.shared.dice import (
    DiceExpression,
    DieSize,
    roll_dice,
    roll_accuracy_difficulty,
    roll_with_advantage,
)
from core.shared.rolls import (
    RollType,
    FlatBonusSource,
    AccuracyDifficulty,
    FlatBonus,
    RollModifiers,
    SkillCheck,
    AttackRoll,
    SaveRoll,
    ContestedCheck,
)
from core.shared.narrative import (
    NarrativeCheckTier,
    NarrativeCheckTierRule,
    NarrativeHelpRule,
    NarrativePushRule,
    NarrativeCheckRules,
    NARRATIVE_TIER_RULES,
    NARRATIVE_TIER_RULES_BY_TIER,
    NARRATIVE_PUSH_RULES,
    DEFAULT_NARRATIVE_CHECK_RULES,
    get_narrative_tier_rule,
)
from core.shared.effects import (
    StatType,
    ConditionType,
    StatModifier,
    DamageModifier,
    RangeModifier,
    ActionGrant,
    Immunity,
    Resistance,
    AccuracyModifier,
    MovementGrant,
    StatusGrant,
    MechanicalEffect,
    stat_bonus,
    damage_bonus,
    immunity_to,
)

__all__ = [
    # Enums
    "ActionType",
    "AttackType",
    "CoverType",
    "DamageType", 
    "RangeType",
    "SizeClass",
    "ManufacturerType",
    "MountType",
    "SystemType",
    "StatusType",
    # Dice
    "DiceExpression",
    "DieSize",
    "roll_dice",
    "roll_accuracy_difficulty",
    "roll_with_advantage",
    # Rolls
    "RollType",
    "FlatBonusSource",
    "AccuracyDifficulty",
    "FlatBonus",
    "RollModifiers",
    "SkillCheck",
    "AttackRoll",
    "SaveRoll",
    "ContestedCheck",
    # Narrative checks
    "NarrativeCheckTier",
    "NarrativeCheckTierRule",
    "NarrativeHelpRule",
    "NarrativePushRule",
    "NarrativeCheckRules",
    "NARRATIVE_TIER_RULES",
    "NARRATIVE_TIER_RULES_BY_TIER",
    "NARRATIVE_PUSH_RULES",
    "DEFAULT_NARRATIVE_CHECK_RULES",
    "get_narrative_tier_rule",
    # Effects
    "StatType",
    "ConditionType",
    "StatModifier",
    "DamageModifier",
    "RangeModifier",
    "ActionGrant",
    "Immunity",
    "Resistance",
    "AccuracyModifier",
    "MovementGrant",
    "StatusGrant",
    "MechanicalEffect",
    "stat_bonus",
    "damage_bonus",
    "immunity_to",
]
