"""
Lancer TTRPG Core Type System

Type-driven schemas for game data, rules, and entities.
Uses Pydantic v2 for validation and JSON Schema export.

Legal Note: This type system encodes game mechanics (allowed under
the Lancer Third Party License), not copyrighted expression/flavor text.
"""

# Re-export pilot domain
from core.pilot import (
    Pilot,
    create_ll0_pilot,
    Skill,
    SkillSet,
    SkillType,
    Background,
    BackgroundInvokeRule,
    Talent,
    TalentDefinition,
    TalentRank,
    License,
    LicenseDefinition,
    Manufacturer,
    CoreBonus,
    CoreBonusDefinition,
    PilotTrigger,
    TriggerDefinition,
    LevelProgression,
    PilotProgressionRules,
    ProgressionIssue,
    ProgressionValidation,
    build_example_pilot_ll0,
    evaluate_example_pilot_ll0,
    build_oda_ll0_pilot,
    build_oda_ll3_pilot,
    evaluate_oda_ll0_example,
    evaluate_oda_ll3_example,
    PilotGearItemDefinition,
    PilotGearRules,
    PilotLoadout,
    PilotCombatBaseStats,
    PilotDamageSeverity,
    DownAndOutRule,
    PilotRestRule,
    PilotCombatRules,
)

# Re-export shared types
from core.shared import (
    ActionType,
    DamageType,
    RangeType,
    SizeClass,
    DiceExpression,
    roll_dice,
    roll_accuracy_difficulty,
    # Effect primitives
    MechanicalEffect,
    StatModifier,
    DamageModifier,
    AccuracyModifier,
    ActionGrant,
    Immunity,
    Resistance,
    # Roll mechanics
    RollType,
    FlatBonusSource,
    AccuracyDifficulty,
    FlatBonus,
    RollModifiers,
    SkillCheck,
    AttackRoll,
    SaveRoll,
    ContestedCheck,
)
from core.mech import (
    WeaponSize,
    WeaponType,
    WeaponDamageType,
    MechWeaponDefinition,
    MountSlotType,
    MountSlot,
    allowed_weapon_sizes,
    CoreSystemDefinition,
    MechFrameBaseStats,
    MechFrameDefinition,
    MechPilotingRules,
    CorePowerRules,
    SystemPointRules,
    DEFAULT_MECH_PILOTING_RULES,
    DEFAULT_CORE_POWER_RULES,
    DEFAULT_SYSTEM_POINT_RULES,
    MountedWeapon,
    InstalledSystem,
    MechBuild,
    MechDerivedStats,
    compute_mech_stats,
    MechBuildIssue,
    MechBuildValidation,
    validate_mech_build,
    build_example_everest_frame,
    build_example_raleigh_frame,
    build_oda_ll0_mech_example,
    build_oda_ll3_mech_example,
    evaluate_oda_ll0_mech_example,
    evaluate_oda_ll3_mech_example,
    compute_oda_ll0_stats,
    compute_oda_ll3_stats,
)

__all__ = [
    # Pilot domain
    "Pilot",
    "create_ll0_pilot",
    "Skill",
    "SkillSet",
    "SkillType",
    "Background",
    "BackgroundInvokeRule",
    "Talent",
    "TalentDefinition",
    "TalentRank",
    "License",
    "LicenseDefinition",
    "Manufacturer",
    "CoreBonus",
    "CoreBonusDefinition",
    "PilotTrigger",
    "TriggerDefinition",
    "LevelProgression",
    "PilotProgressionRules",
    "ProgressionIssue",
    "ProgressionValidation",
    "build_example_pilot_ll0",
    "evaluate_example_pilot_ll0",
    "build_oda_ll0_pilot",
    "build_oda_ll3_pilot",
    "evaluate_oda_ll0_example",
    "evaluate_oda_ll3_example",
    "PilotGearItemDefinition",
    "PilotGearRules",
    "PilotLoadout",
    "PilotCombatBaseStats",
    "PilotDamageSeverity",
    "DownAndOutRule",
    "PilotRestRule",
    "PilotCombatRules",
    # Shared types
    "ActionType",
    "DamageType",
    "RangeType",
    "SizeClass",
    "DiceExpression",
    "roll_dice",
    "roll_accuracy_difficulty",
    # Effect primitives
    "MechanicalEffect",
    "StatModifier",
    "DamageModifier",
    "AccuracyModifier",
    "ActionGrant",
    "Immunity",
    "Resistance",
    # Roll mechanics
    "RollType",
    "FlatBonusSource",
    "AccuracyDifficulty",
    "FlatBonus",
    "RollModifiers",
    "SkillCheck",
    "AttackRoll",
    "SaveRoll",
    "ContestedCheck",
    # Mech domain
    "WeaponSize",
    "WeaponType",
    "WeaponDamageType",
    "MechWeaponDefinition",
    "MountSlotType",
    "MountSlot",
    "allowed_weapon_sizes",
    "CoreSystemDefinition",
    "MechFrameBaseStats",
    "MechFrameDefinition",
    "MechPilotingRules",
    "CorePowerRules",
    "SystemPointRules",
    "DEFAULT_MECH_PILOTING_RULES",
    "DEFAULT_CORE_POWER_RULES",
    "DEFAULT_SYSTEM_POINT_RULES",
    "MountedWeapon",
    "InstalledSystem",
    "MechBuild",
    "MechDerivedStats",
    "compute_mech_stats",
    "MechBuildIssue",
    "MechBuildValidation",
    "validate_mech_build",
    "build_example_everest_frame",
    "build_example_raleigh_frame",
    "build_oda_ll0_mech_example",
    "build_oda_ll3_mech_example",
    "evaluate_oda_ll0_mech_example",
    "evaluate_oda_ll3_mech_example",
    "compute_oda_ll0_stats",
    "compute_oda_ll3_stats",
]
