"""Pilot domain models for Lancer TTRPG."""

from core.pilot.skill import (
    Skill,
    SkillSet,
    SkillType,
    SKILLS,
    TriggerDefinition,
    PilotTrigger,
    TRIGGER_DEFINITIONS,
    get_trigger_definition,
)
from core.pilot.background import (
    Background,
    BackgroundInvokeRule,
    BACKGROUND_INVOKE_RULE,
    PILOT_BACKGROUNDS,
    get_background,
)
from core.pilot.talent import (
    Talent,
    TalentRank,
    TalentDefinition,
    EXAMPLE_TALENTS,
    get_talent_definition,
)
from core.pilot.license import (
    License,
    LicenseDefinition,
    Manufacturer,
    MANUFACTURER_NAMES,
    EXAMPLE_LICENSES,
    get_license_definition,
    get_licenses_by_manufacturer,
)
from core.pilot.core_bonus import (
    CoreBonus,
    CoreBonusDefinition,
    ALL_CORE_BONUSES,
    get_core_bonus_definition,
    get_core_bonuses_by_manufacturer,
)
from core.pilot.pilot import Pilot, create_ll0_pilot
from core.pilot.progression import (
    LEVEL_CAP,
    LevelProgression,
    PilotProgressionRules,
    DEFAULT_PILOT_PROGRESSION,
    LICENSE_LEVEL_TABLE,
    get_level_progression,
)
from core.pilot.mission import (
    MissionPhaseType,
    DowntimeActionCategory,
    DowntimeOutcomeType,
    ReserveSource,
    MissionCadenceRules,
    DEFAULT_MISSION_CADENCE_RULES,
    ReserveEntry,
    DowntimeActionDefinition,
    DowntimeActionUse,
    DowntimePlan,
    DowntimeIssue,
    DowntimeValidation,
    DOWNTIME_ACTION_DEFINITIONS,
    DOWNTIME_ACTIONS_BY_ID,
    get_downtime_action_definition,
    validate_downtime_plan,
)
from core.pilot.validation import ProgressionIssue, ProgressionValidation, validate_pilot_progression
from core.pilot.examples import (
    build_example_pilot_ll0,
    evaluate_example_pilot_ll0,
    build_example_downtime_plan,
    evaluate_example_downtime_plan,
    build_oda_ll0_pilot,
    build_oda_ll3_pilot,
    evaluate_oda_ll0_example,
    evaluate_oda_ll3_example,
)
from core.pilot.gear import (
    PilotGearItemDefinition,
    PilotGearRules,
    DEFAULT_PILOT_GEAR_RULES,
    PilotLoadout,
    PilotGearCategory,
    PilotGearTag,
    PilotGearTagType,
    PilotDamageSpec,
    PilotAreaEffect,
    PilotGrenadePayload,
    PilotChargePayload,
    PilotFlightEffect,
    PilotMedicalEffect,
    PilotStimEffect,
    PILOT_GEAR_DEFINITIONS,
    PILOT_GEAR_DEFINITIONS_BY_ID,
    get_pilot_gear_definition,
    PilotGearIssue,
    PilotGearValidation,
    validate_pilot_loadout,
    get_pilot_gear_stat_mods,
)
from core.pilot.combat import (
    PilotCombatBaseStats,
    DEFAULT_PILOT_COMBAT_STATS,
    PilotDamageSeverity,
    PILOT_DAMAGE_SEVERITY_BANDS,
    DownAndOutRule,
    DEFAULT_DOWN_AND_OUT_RULE,
    PilotRestRule,
    DEFAULT_PILOT_REST_RULE,
    PilotCombatRules,
    DEFAULT_PILOT_COMBAT_RULES,
    PilotInMechCombatRules,
    DEFAULT_PILOT_IN_MECH_RULES,
)

__all__ = [
    # Main model
    "Pilot",
    "create_ll0_pilot",
    # Skills
    "Skill",
    "SkillSet",
    "SkillType",
    "SKILLS",
    "TriggerDefinition",
    "PilotTrigger",
    "TRIGGER_DEFINITIONS",
    "get_trigger_definition",
    # Backgrounds
    "Background",
    "BackgroundInvokeRule",
    "BACKGROUND_INVOKE_RULE",
    "PILOT_BACKGROUNDS",
    "get_background",
    # Talents
    "Talent",
    "TalentRank",
    "TalentDefinition",
    "EXAMPLE_TALENTS",
    "get_talent_definition",
    # Licenses
    "License",
    "LicenseDefinition",
    "Manufacturer",
    "MANUFACTURER_NAMES",
    "EXAMPLE_LICENSES",
    "get_license_definition",
    "get_licenses_by_manufacturer",
    # Core Bonuses
    "CoreBonus",
    "CoreBonusDefinition",
    "ALL_CORE_BONUSES",
    "get_core_bonus_definition",
    "get_core_bonuses_by_manufacturer",
    # Progression
    "LEVEL_CAP",
    "LevelProgression",
    "PilotProgressionRules",
    "DEFAULT_PILOT_PROGRESSION",
    "LICENSE_LEVEL_TABLE",
    "get_level_progression",
    # Missions / Downtime
    "MissionPhaseType",
    "DowntimeActionCategory",
    "DowntimeOutcomeType",
    "ReserveSource",
    "MissionCadenceRules",
    "DEFAULT_MISSION_CADENCE_RULES",
    "ReserveEntry",
    "DowntimeActionDefinition",
    "DowntimeActionUse",
    "DowntimePlan",
    "DowntimeIssue",
    "DowntimeValidation",
    "DOWNTIME_ACTION_DEFINITIONS",
    "DOWNTIME_ACTIONS_BY_ID",
    "get_downtime_action_definition",
    "validate_downtime_plan",
    # Validation
    "ProgressionIssue",
    "ProgressionValidation",
    "validate_pilot_progression",
    # Examples
    "build_example_pilot_ll0",
    "evaluate_example_pilot_ll0",
    "build_example_downtime_plan",
    "evaluate_example_downtime_plan",
    "build_oda_ll0_pilot",
    "build_oda_ll3_pilot",
    "evaluate_oda_ll0_example",
    "evaluate_oda_ll3_example",
    # Gear
    "PilotGearItemDefinition",
    "PilotGearRules",
    "DEFAULT_PILOT_GEAR_RULES",
    "PilotLoadout",
    "PilotGearCategory",
    "PilotGearTag",
    "PilotGearTagType",
    "PilotDamageSpec",
    "PilotAreaEffect",
    "PilotGrenadePayload",
    "PilotChargePayload",
    "PilotFlightEffect",
    "PilotMedicalEffect",
    "PilotStimEffect",
    "PILOT_GEAR_DEFINITIONS",
    "PILOT_GEAR_DEFINITIONS_BY_ID",
    "get_pilot_gear_definition",
    "PilotGearIssue",
    "PilotGearValidation",
    "validate_pilot_loadout",
    "get_pilot_gear_stat_mods",
    # Combat
    "PilotCombatBaseStats",
    "DEFAULT_PILOT_COMBAT_STATS",
    "PilotDamageSeverity",
    "PILOT_DAMAGE_SEVERITY_BANDS",
    "DownAndOutRule",
    "DEFAULT_DOWN_AND_OUT_RULE",
    "PilotRestRule",
    "DEFAULT_PILOT_REST_RULE",
    "PilotCombatRules",
    "DEFAULT_PILOT_COMBAT_RULES",
    "PilotInMechCombatRules",
    "DEFAULT_PILOT_IN_MECH_RULES",
]
