/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuartersIndexRouteImport } from './routes/quarters/index'
import { Route as PilotsIndexRouteImport } from './routes/pilots/index'
import { Route as CompendiumIndexRouteImport } from './routes/compendium/index'
import { Route as CharactersIndexRouteImport } from './routes/characters/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns/index'
import { Route as QuartersPilotRouteImport } from './routes/quarters/pilot'
import { Route as QuartersMechRouteImport } from './routes/quarters/mech'
import { Route as PilotsNewRouteImport } from './routes/pilots/new'
import { Route as PilotsPilotIdRouteImport } from './routes/pilots/$pilotId'
import { Route as InvitesTokenRouteImport } from './routes/invites/$token'
import { Route as CombatCombatIdRouteImport } from './routes/combat/$combatId'
import { Route as CharactersNewRouteImport } from './routes/characters/new'
import { Route as CharactersCharacterIdRouteImport } from './routes/characters/$characterId'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns/$campaignId'
import { Route as CharactersCharacterIdExportRouteImport } from './routes/characters/$characterId.export'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuartersIndexRoute = QuartersIndexRouteImport.update({
  id: '/quarters/',
  path: '/quarters/',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotsIndexRoute = PilotsIndexRouteImport.update({
  id: '/pilots/',
  path: '/pilots/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompendiumIndexRoute = CompendiumIndexRouteImport.update({
  id: '/compendium/',
  path: '/compendium/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuartersPilotRoute = QuartersPilotRouteImport.update({
  id: '/quarters/pilot',
  path: '/quarters/pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const QuartersMechRoute = QuartersMechRouteImport.update({
  id: '/quarters/mech',
  path: '/quarters/mech',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotsNewRoute = PilotsNewRouteImport.update({
  id: '/pilots/new',
  path: '/pilots/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotsPilotIdRoute = PilotsPilotIdRouteImport.update({
  id: '/pilots/$pilotId',
  path: '/pilots/$pilotId',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitesTokenRoute = InvitesTokenRouteImport.update({
  id: '/invites/$token',
  path: '/invites/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CombatCombatIdRoute = CombatCombatIdRouteImport.update({
  id: '/combat/$combatId',
  path: '/combat/$combatId',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersNewRoute = CharactersNewRouteImport.update({
  id: '/characters/new',
  path: '/characters/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersCharacterIdRoute = CharactersCharacterIdRouteImport.update({
  id: '/characters/$characterId',
  path: '/characters/$characterId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersCharacterIdExportRoute =
  CharactersCharacterIdExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => CharactersCharacterIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/characters/$characterId': typeof CharactersCharacterIdRouteWithChildren
  '/characters/new': typeof CharactersNewRoute
  '/combat/$combatId': typeof CombatCombatIdRoute
  '/invites/$token': typeof InvitesTokenRoute
  '/pilots/$pilotId': typeof PilotsPilotIdRoute
  '/pilots/new': typeof PilotsNewRoute
  '/quarters/mech': typeof QuartersMechRoute
  '/quarters/pilot': typeof QuartersPilotRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/characters': typeof CharactersIndexRoute
  '/compendium': typeof CompendiumIndexRoute
  '/pilots': typeof PilotsIndexRoute
  '/quarters': typeof QuartersIndexRoute
  '/characters/$characterId/export': typeof CharactersCharacterIdExportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/characters/$characterId': typeof CharactersCharacterIdRouteWithChildren
  '/characters/new': typeof CharactersNewRoute
  '/combat/$combatId': typeof CombatCombatIdRoute
  '/invites/$token': typeof InvitesTokenRoute
  '/pilots/$pilotId': typeof PilotsPilotIdRoute
  '/pilots/new': typeof PilotsNewRoute
  '/quarters/mech': typeof QuartersMechRoute
  '/quarters/pilot': typeof QuartersPilotRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/characters': typeof CharactersIndexRoute
  '/compendium': typeof CompendiumIndexRoute
  '/pilots': typeof PilotsIndexRoute
  '/quarters': typeof QuartersIndexRoute
  '/characters/$characterId/export': typeof CharactersCharacterIdExportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/characters/$characterId': typeof CharactersCharacterIdRouteWithChildren
  '/characters/new': typeof CharactersNewRoute
  '/combat/$combatId': typeof CombatCombatIdRoute
  '/invites/$token': typeof InvitesTokenRoute
  '/pilots/$pilotId': typeof PilotsPilotIdRoute
  '/pilots/new': typeof PilotsNewRoute
  '/quarters/mech': typeof QuartersMechRoute
  '/quarters/pilot': typeof QuartersPilotRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/characters/': typeof CharactersIndexRoute
  '/compendium/': typeof CompendiumIndexRoute
  '/pilots/': typeof PilotsIndexRoute
  '/quarters/': typeof QuartersIndexRoute
  '/characters/$characterId/export': typeof CharactersCharacterIdExportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaigns/$campaignId'
    | '/characters/$characterId'
    | '/characters/new'
    | '/combat/$combatId'
    | '/invites/$token'
    | '/pilots/$pilotId'
    | '/pilots/new'
    | '/quarters/mech'
    | '/quarters/pilot'
    | '/campaigns'
    | '/characters'
    | '/compendium'
    | '/pilots'
    | '/quarters'
    | '/characters/$characterId/export'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaigns/$campaignId'
    | '/characters/$characterId'
    | '/characters/new'
    | '/combat/$combatId'
    | '/invites/$token'
    | '/pilots/$pilotId'
    | '/pilots/new'
    | '/quarters/mech'
    | '/quarters/pilot'
    | '/campaigns'
    | '/characters'
    | '/compendium'
    | '/pilots'
    | '/quarters'
    | '/characters/$characterId/export'
  id:
    | '__root__'
    | '/'
    | '/campaigns/$campaignId'
    | '/characters/$characterId'
    | '/characters/new'
    | '/combat/$combatId'
    | '/invites/$token'
    | '/pilots/$pilotId'
    | '/pilots/new'
    | '/quarters/mech'
    | '/quarters/pilot'
    | '/campaigns/'
    | '/characters/'
    | '/compendium/'
    | '/pilots/'
    | '/quarters/'
    | '/characters/$characterId/export'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRoute
  CharactersCharacterIdRoute: typeof CharactersCharacterIdRouteWithChildren
  CharactersNewRoute: typeof CharactersNewRoute
  CombatCombatIdRoute: typeof CombatCombatIdRoute
  InvitesTokenRoute: typeof InvitesTokenRoute
  PilotsPilotIdRoute: typeof PilotsPilotIdRoute
  PilotsNewRoute: typeof PilotsNewRoute
  QuartersMechRoute: typeof QuartersMechRoute
  QuartersPilotRoute: typeof QuartersPilotRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
  CompendiumIndexRoute: typeof CompendiumIndexRoute
  PilotsIndexRoute: typeof PilotsIndexRoute
  QuartersIndexRoute: typeof QuartersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quarters/': {
      id: '/quarters/'
      path: '/quarters'
      fullPath: '/quarters'
      preLoaderRoute: typeof QuartersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilots/': {
      id: '/pilots/'
      path: '/pilots'
      fullPath: '/pilots'
      preLoaderRoute: typeof PilotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compendium/': {
      id: '/compendium/'
      path: '/compendium'
      fullPath: '/compendium'
      preLoaderRoute: typeof CompendiumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quarters/pilot': {
      id: '/quarters/pilot'
      path: '/quarters/pilot'
      fullPath: '/quarters/pilot'
      preLoaderRoute: typeof QuartersPilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quarters/mech': {
      id: '/quarters/mech'
      path: '/quarters/mech'
      fullPath: '/quarters/mech'
      preLoaderRoute: typeof QuartersMechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilots/new': {
      id: '/pilots/new'
      path: '/pilots/new'
      fullPath: '/pilots/new'
      preLoaderRoute: typeof PilotsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilots/$pilotId': {
      id: '/pilots/$pilotId'
      path: '/pilots/$pilotId'
      fullPath: '/pilots/$pilotId'
      preLoaderRoute: typeof PilotsPilotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invites/$token': {
      id: '/invites/$token'
      path: '/invites/$token'
      fullPath: '/invites/$token'
      preLoaderRoute: typeof InvitesTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combat/$combatId': {
      id: '/combat/$combatId'
      path: '/combat/$combatId'
      fullPath: '/combat/$combatId'
      preLoaderRoute: typeof CombatCombatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/new': {
      id: '/characters/new'
      path: '/characters/new'
      fullPath: '/characters/new'
      preLoaderRoute: typeof CharactersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$characterId': {
      id: '/characters/$characterId'
      path: '/characters/$characterId'
      fullPath: '/characters/$characterId'
      preLoaderRoute: typeof CharactersCharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$characterId/export': {
      id: '/characters/$characterId/export'
      path: '/export'
      fullPath: '/characters/$characterId/export'
      preLoaderRoute: typeof CharactersCharacterIdExportRouteImport
      parentRoute: typeof CharactersCharacterIdRoute
    }
  }
}

interface CharactersCharacterIdRouteChildren {
  CharactersCharacterIdExportRoute: typeof CharactersCharacterIdExportRoute
}

const CharactersCharacterIdRouteChildren: CharactersCharacterIdRouteChildren = {
  CharactersCharacterIdExportRoute: CharactersCharacterIdExportRoute,
}

const CharactersCharacterIdRouteWithChildren =
  CharactersCharacterIdRoute._addFileChildren(
    CharactersCharacterIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRoute,
  CharactersCharacterIdRoute: CharactersCharacterIdRouteWithChildren,
  CharactersNewRoute: CharactersNewRoute,
  CombatCombatIdRoute: CombatCombatIdRoute,
  InvitesTokenRoute: InvitesTokenRoute,
  PilotsPilotIdRoute: PilotsPilotIdRoute,
  PilotsNewRoute: PilotsNewRoute,
  QuartersMechRoute: QuartersMechRoute,
  QuartersPilotRoute: QuartersPilotRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  CharactersIndexRoute: CharactersIndexRoute,
  CompendiumIndexRoute: CompendiumIndexRoute,
  PilotsIndexRoute: PilotsIndexRoute,
  QuartersIndexRoute: QuartersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
