"""Combat turn execution and action resolution.

Provides pure functions for executing combat turns:
- Turn initialization (reset economy, expire prepared actions, decrement cooldowns)
- Action execution (validate economy, resolve effects, apply mutations)
- Turn finalization (end-of-turn effects, advance sequence)

All functions are pure - they take state and return new state + results.
The API layer handles persistence.
"""

from __future__ import annotations

from typing import Literal
from pydantic import Field
from core.shared.models import FrozenModel

from core.shared.enums import ActionType, StatusType
from core.mech.combat_state import (
    MechCombatScenario,
    CombatantState,
    CombatResources,
    CombatTurn,
    CombatRound,
    ActionUse,
    OverchargeState,
)
from core.mech.action_economy import (
    ActionEconomyState,
    validate_action_economy,
    use_full_action,
    use_quick_action,
    use_overcharge as mark_overcharge_used,
    use_reaction,
    reset_economy_for_new_turn,
)
from core.mech.combat_resolution import (
    decrement_cooldowns_on_turn_start,
    decrement_cooldowns_on_turn_end,
    reset_per_round_reactions,
    consume_per_round_reaction,
    increment_overcharge_on_turn_start,
)
from core.mech.grid import HexPosition


# =============================================================================
# Input/Output Models
# =============================================================================


class ActionExecutionInput(FrozenModel):
    """Input for executing a combat action."""

    actor_id: str = Field(..., description="ID of the combatant taking action")
    action_id: str = Field(..., description="Action identifier (e.g., 'skirmish', 'barrage')")
    action_type: ActionType = Field(..., description="Type of action")
    target_ids: list[str] = Field(default_factory=list, description="Target combatant IDs")
    target_position: HexPosition | None = Field(default=None, description="Target position for area/movement")
    weapon_id: str | None = Field(default=None, description="Weapon being used")
    system_id: str | None = Field(default=None, description="System being activated")
    movement_path: list[HexPosition] = Field(default_factory=list, description="Movement path for move actions")
    is_overcharge: bool = Field(default=False, description="Whether this action uses overcharge")
    granted_by_overcharge: bool = Field(default=False, description="Whether this action was granted by overcharge")


class ResourceChange(FrozenModel):
    """Change to a combatant's resources."""

    combatant_id: str
    hp_change: int = 0
    heat_change: int = 0
    structure_change: int = 0
    stress_change: int = 0
    repairs_change: int = 0


class ActionExecutionResult(FrozenModel):
    """Result of executing a combat action."""

    success: bool = Field(..., description="Whether action executed successfully")
    error: str | None = Field(default=None, description="Error message if failed")
    action_use: ActionUse | None = Field(default=None, description="Recorded action for combat log")
    effects_applied: list[dict] = Field(default_factory=list, description="Effects that were applied")
    damage_dealt: int = Field(default=0, description="Total damage dealt")
    heat_generated: int = Field(default=0, description="Heat generated by this action")
    resource_changes: list[ResourceChange] = Field(
        default_factory=list, description="Resource changes to combatants"
    )
    statuses_applied: dict[str, list[StatusType]] = Field(
        default_factory=dict, description="Statuses applied to targets"
    )


class TurnStartResult(FrozenModel):
    """Result of starting a combatant's turn."""

    actor_id: str = Field(..., description="ID of the actor whose turn started")
    actor_name: str = Field(..., description="Name of the actor")
    economy: ActionEconomyState = Field(..., description="Fresh action economy for this turn")
    available_actions: list[str] = Field(default_factory=list, description="Actions available to this actor")
    prepared_action_expired: bool = Field(default=False, description="Whether a prepared action expired")
    cooldowns_decremented: list[str] = Field(
        default_factory=list, description="Effect IDs whose cooldowns were decremented"
    )


class TurnEndResult(FrozenModel):
    """Result of ending a combatant's turn."""

    actor_id: str = Field(..., description="ID of the actor whose turn ended")
    next_actor_id: str | None = Field(default=None, description="ID of next actor, None if round ends")
    next_actor_name: str | None = Field(default=None, description="Name of next actor")
    round_advanced: bool = Field(default=False, description="Whether we advanced to a new round")
    new_round_number: int | None = Field(default=None, description="New round number if advanced")
    end_of_turn_effects: list[dict] = Field(default_factory=list, description="Effects applied at turn end")
    cooldowns_decremented: list[str] = Field(
        default_factory=list, description="Effect IDs whose cooldowns were decremented"
    )


class ReactionInput(FrozenModel):
    """Input for declaring a reaction."""

    reactor_id: str = Field(..., description="ID of the reacting combatant")
    reaction_type: Literal["brace", "overwatch"] = Field(..., description="Type of reaction")
    trigger_action_id: str | None = Field(default=None, description="Action that triggered this reaction")
    target_ids: list[str] = Field(default_factory=list, description="Targets for reaction (e.g., overwatch)")
    weapon_id: str | None = Field(default=None, description="Weapon for overwatch attack")


class ReactionResult(FrozenModel):
    """Result of declaring a reaction."""

    success: bool = Field(..., description="Whether reaction was valid")
    error: str | None = Field(default=None, description="Error message if failed")
    reaction_used: str | None = Field(default=None, description="Reaction type that was used")
    effects_applied: list[dict] = Field(default_factory=list, description="Effects from the reaction")
    damage_dealt: int = Field(default=0, description="Damage dealt by overwatch")


class AvailableAction(FrozenModel):
    """An action available to the current actor."""

    action_id: str = Field(..., description="Action identifier")
    action_name: str = Field(..., description="Display name")
    action_type: ActionType = Field(..., description="Action type (full/quick/free/reaction)")
    is_available: bool = Field(..., description="Whether action can be taken now")
    unavailable_reason: str | None = Field(default=None, description="Why action is unavailable")
    requires_target: bool = Field(default=False, description="Whether action needs a target")
    requires_weapon: bool = Field(default=False, description="Whether action needs a weapon")


class AvailableActionsResult(FrozenModel):
    """Available actions for the current actor."""

    actor_id: str = Field(..., description="Actor these actions are for")
    economy: ActionEconomyState = Field(..., description="Current action economy state")
    full_actions: list[AvailableAction] = Field(default_factory=list)
    quick_actions: list[AvailableAction] = Field(default_factory=list)
    free_actions: list[AvailableAction] = Field(default_factory=list)
    reactions: list[AvailableAction] = Field(default_factory=list)
    protocols: list[AvailableAction] = Field(default_factory=list)
    can_overcharge: bool = Field(default=True, description="Whether overcharge is available")


# =============================================================================
# Turn Management Functions
# =============================================================================


def get_current_actor(
    scenario: MechCombatScenario,
    current_round: int,
    current_turn_index: int,
) -> CombatantState | None:
    """Get the combatant whose turn it currently is.

    Args:
        scenario: Current combat scenario
        current_round: Current round number (1-indexed)
        current_turn_index: Current turn index within the round (0-indexed)

    Returns:
        CombatantState for current actor, or None if not found
    """
    if not scenario.rounds:
        return None

    round_idx = current_round - 1
    if round_idx < 0 or round_idx >= len(scenario.rounds):
        return None

    current_round_data = scenario.rounds[round_idx]
    if current_turn_index >= len(current_round_data.turns):
        return None

    actor_id = current_round_data.turns[current_turn_index].actor_id

    for combatant in scenario.combatants:
        if combatant.id == actor_id:
            return combatant

    return None


def start_turn(
    scenario: MechCombatScenario,
    actor_id: str,
) -> tuple[MechCombatScenario, TurnStartResult]:
    """Initialize a combatant's turn.

    This function:
    - Resets the action economy for the new turn
    - Expires any prepared actions
    - Decrements cooldowns that trigger on turn start
    - Resets overcharge uses for the turn

    Args:
        scenario: Current combat scenario
        actor_id: ID of the combatant starting their turn

    Returns:
        Tuple of (updated scenario, TurnStartResult)
    """
    # Find the actor
    actor: CombatantState | None = None
    actor_index: int = -1
    for i, c in enumerate(scenario.combatants):
        if c.id == actor_id:
            actor = c
            actor_index = i
            break

    if actor is None:
        # Return unchanged scenario with error result
        return scenario, TurnStartResult(
            actor_id=actor_id,
            actor_name="Unknown",
            economy=ActionEconomyState(),
            available_actions=[],
            prepared_action_expired=False,
        )

    # Initialize fresh action economy
    economy = ActionEconomyState()

    # Check for prepared action expiration
    prepared_action_expired = False
    updated_actor = actor
    if actor.prepared_action is not None:
        prepared_action_expired = True
        updated_actor = actor.model_copy(update={"prepared_action": None})

    # Decrement cooldowns
    cooldowns_decremented: list[str] = []
    if updated_actor.cooldown_states:
        mutable_cooldowns = dict(updated_actor.cooldown_states)
        results = decrement_cooldowns_on_turn_start(actor_cooldown_states=mutable_cooldowns)
        cooldowns_decremented = [r.effect_id for r in results if r.was_decremented]
        updated_actor = updated_actor.model_copy(update={"cooldown_states": mutable_cooldowns})

    # Reset overcharge uses for the turn
    if updated_actor.overcharge_state is not None:
        new_overcharge_state = increment_overcharge_on_turn_start(updated_actor.overcharge_state)
        updated_actor = updated_actor.model_copy(update={"overcharge_state": new_overcharge_state})

    # Build updated combatants list
    updated_combatants = list(scenario.combatants)
    updated_combatants[actor_index] = updated_actor

    # Build updated scenario
    updated_scenario = MechCombatScenario(
        combatants=updated_combatants,
        grapples=list(scenario.grapples),
        rounds=list(scenario.rounds),
        terrain=scenario.terrain,
        environment=scenario.environment,
        deployables=dict(scenario.deployables),
    )

    # Determine available actions
    available_actions = _get_basic_available_actions(updated_actor)

    return updated_scenario, TurnStartResult(
        actor_id=actor_id,
        actor_name=actor.name,
        economy=economy,
        available_actions=available_actions,
        prepared_action_expired=prepared_action_expired,
        cooldowns_decremented=cooldowns_decremented,
    )


def end_turn(
    scenario: MechCombatScenario,
    current_round: int,
    current_turn_index: int,
    current_turn: CombatTurn,
) -> tuple[MechCombatScenario, TurnEndResult, int, int]:
    """Finalize a combatant's turn and determine the next actor.

    This function:
    - Applies end-of-turn effects
    - Decrements cooldowns that trigger on turn end
    - Determines the next actor or advances the round

    Args:
        scenario: Current combat scenario
        current_round: Current round number (1-indexed)
        current_turn_index: Current turn index (0-indexed)
        current_turn: The turn being ended

    Returns:
        Tuple of (updated scenario, TurnEndResult, new_round, new_turn_index)
    """
    actor_id = current_turn.actor_id

    # Find the actor
    actor: CombatantState | None = None
    actor_index: int = -1
    for i, c in enumerate(scenario.combatants):
        if c.id == actor_id:
            actor = c
            actor_index = i
            break

    end_of_turn_effects: list[dict] = []
    cooldowns_decremented: list[str] = []
    updated_actor = actor

    if actor is not None:
        # Decrement cooldowns on turn end
        if actor.cooldown_states:
            mutable_cooldowns = dict(actor.cooldown_states)
            results = decrement_cooldowns_on_turn_end(actor_cooldown_states=mutable_cooldowns)
            cooldowns_decremented = [r.effect_id for r in results if r.was_decremented]
            updated_actor = actor.model_copy(update={"cooldown_states": mutable_cooldowns})

    # Update combatants if actor was modified
    updated_combatants = list(scenario.combatants)
    if updated_actor is not None and actor_index >= 0:
        updated_combatants[actor_index] = updated_actor

    # Get current round data
    round_idx = current_round - 1
    current_round_data = scenario.rounds[round_idx] if round_idx < len(scenario.rounds) else None

    # Determine next actor
    next_turn_index = current_turn_index + 1
    next_round = current_round
    round_advanced = False
    next_actor_id: str | None = None
    next_actor_name: str | None = None

    if current_round_data and next_turn_index < len(current_round_data.turns):
        # More turns in this round
        next_actor_id = current_round_data.turns[next_turn_index].actor_id
        for c in updated_combatants:
            if c.id == next_actor_id:
                next_actor_name = c.name
                break
    else:
        # Round ends, advance to next round
        round_advanced = True
        next_round = current_round + 1
        next_turn_index = 0

        # Reset per-round reactions for all combatants
        reset_combatants: list[CombatantState] = []
        for c in updated_combatants:
            reset_combatants.append(reset_per_round_reactions(c))
        updated_combatants = reset_combatants

        # Check if there's a next round
        if next_round - 1 < len(scenario.rounds):
            next_round_data = scenario.rounds[next_round - 1]
            if next_round_data.turns:
                next_actor_id = next_round_data.turns[0].actor_id
                for c in updated_combatants:
                    if c.id == next_actor_id:
                        next_actor_name = c.name
                        break

    # Build updated scenario
    updated_scenario = MechCombatScenario(
        combatants=updated_combatants,
        grapples=list(scenario.grapples),
        rounds=list(scenario.rounds),
        terrain=scenario.terrain,
        environment=scenario.environment,
        deployables=dict(scenario.deployables),
    )

    result = TurnEndResult(
        actor_id=actor_id,
        next_actor_id=next_actor_id,
        next_actor_name=next_actor_name,
        round_advanced=round_advanced,
        new_round_number=next_round if round_advanced else None,
        end_of_turn_effects=end_of_turn_effects,
        cooldowns_decremented=cooldowns_decremented,
    )

    return updated_scenario, result, next_round, next_turn_index


# =============================================================================
# Action Execution Functions
# =============================================================================


def execute_action(
    scenario: MechCombatScenario,
    current_turn: CombatTurn,
    economy: ActionEconomyState,
    action_input: ActionExecutionInput,
) -> tuple[MechCombatScenario, CombatTurn, ActionEconomyState, ActionExecutionResult]:
    """Execute a combat action.

    This function:
    - Validates the action against the current economy
    - Resolves the action effects
    - Updates the scenario with results
    - Records the action in the turn log

    Args:
        scenario: Current combat scenario
        current_turn: Current turn being played
        economy: Current action economy state
        action_input: The action to execute

    Returns:
        Tuple of (updated scenario, updated turn, updated economy, ActionExecutionResult)
    """
    # Validate action economy
    validation = validate_action_economy(
        economy,
        action_input.action_type,
        is_overcharge=action_input.is_overcharge,
    )

    if not validation.can_take_action:
        return scenario, current_turn, economy, ActionExecutionResult(
            success=False,
            error=validation.errors[0] if validation.errors else "Action not available",
        )

    # Find the actor
    actor: CombatantState | None = None
    for c in scenario.combatants:
        if c.id == action_input.actor_id:
            actor = c
            break

    if actor is None:
        return scenario, current_turn, economy, ActionExecutionResult(
            success=False,
            error=f"Actor {action_input.actor_id} not found",
        )

    # Update economy based on action type
    updated_economy = economy
    if action_input.action_type == "full":
        updated_economy = use_full_action(economy)
    elif action_input.action_type == "quick":
        updated_economy = use_quick_action(economy)
    elif action_input.is_overcharge:
        updated_economy = mark_overcharge_used(economy)

    # Create action record
    action_use = ActionUse(
        action_id=action_input.action_id,
        action_type=action_input.action_type,
        target_ids=action_input.target_ids,
        target_position=action_input.target_position,
        granted_by_overcharge=action_input.granted_by_overcharge,
    )

    # Record action in turn
    updated_actions = list(current_turn.actions) + [action_use]
    updated_turn = CombatTurn(
        actor_id=current_turn.actor_id,
        move_used=current_turn.move_used or (action_input.action_id == "move"),
        movement_mode=current_turn.movement_mode,
        movement_path=current_turn.movement_path,
        actions=updated_actions,
    )

    # Apply action effects (simplified - real implementation would call combat_helpers)
    resource_changes: list[ResourceChange] = []
    effects_applied: list[dict] = []
    damage_dealt = 0
    heat_generated = 0
    statuses_applied: dict[str, list[StatusType]] = {}

    # Handle overcharge heat
    if action_input.is_overcharge and actor.overcharge_state is not None:
        from core.mech.combat_resolution import use_overcharge as apply_overcharge
        new_overcharge_state, overcharge_result = apply_overcharge(actor.overcharge_state)
        heat_generated = overcharge_result.rolled_cost or 0

        # Update actor's overcharge state and heat
        actor_idx = next(i for i, c in enumerate(scenario.combatants) if c.id == actor.id)
        new_heat = actor.resources.heat_current + heat_generated
        new_resources = actor.resources.model_copy(update={"heat_current": new_heat})
        updated_actor = actor.model_copy(
            update={
                "overcharge_state": new_overcharge_state,
                "resources": new_resources,
            }
        )
        updated_combatants = list(scenario.combatants)
        updated_combatants[actor_idx] = updated_actor

        scenario = MechCombatScenario(
            combatants=updated_combatants,
            grapples=list(scenario.grapples),
            rounds=list(scenario.rounds),
            terrain=scenario.terrain,
            environment=scenario.environment,
            deployables=dict(scenario.deployables),
        )

        resource_changes.append(ResourceChange(
            combatant_id=actor.id,
            heat_change=heat_generated,
        ))
        effects_applied.append({
            "type": "overcharge",
            "heat": heat_generated,
            "new_level": new_overcharge_state.current_level,
        })

    result = ActionExecutionResult(
        success=True,
        action_use=action_use,
        effects_applied=effects_applied,
        damage_dealt=damage_dealt,
        heat_generated=heat_generated,
        resource_changes=resource_changes,
        statuses_applied=statuses_applied,
    )

    return scenario, updated_turn, updated_economy, result


def execute_reaction(
    scenario: MechCombatScenario,
    economy: ActionEconomyState,
    reaction_input: ReactionInput,
) -> tuple[MechCombatScenario, ActionEconomyState, ReactionResult]:
    """Execute a reaction.

    Args:
        scenario: Current combat scenario
        economy: Current action economy (for the reacting combatant)
        reaction_input: The reaction to execute

    Returns:
        Tuple of (updated scenario, updated economy, ReactionResult)
    """
    # Find the reactor
    reactor: CombatantState | None = None
    reactor_idx: int = -1
    for i, c in enumerate(scenario.combatants):
        if c.id == reaction_input.reactor_id:
            reactor = c
            reactor_idx = i
            break

    if reactor is None:
        return scenario, economy, ReactionResult(
            success=False,
            error=f"Reactor {reaction_input.reactor_id} not found",
        )

    # Check if reaction is available this round
    max_per_round = 1  # Standard reactions are 1/round
    reaction_result = consume_per_round_reaction(
        reactor,
        reaction_input.reaction_type,
        max_per_round,
    )

    if not reaction_result.success:
        return scenario, economy, ReactionResult(
            success=False,
            error=reaction_result.message,
        )

    # Use reaction in economy
    updated_economy = use_reaction(economy)

    # Update reactor's per-round reaction tracking
    new_per_round = dict(reactor.per_round_reactions)
    current_count = new_per_round.get(reaction_input.reaction_type, 0)
    new_per_round[reaction_input.reaction_type] = current_count + 1
    updated_reactor = reactor.model_copy(update={"per_round_reactions": new_per_round})

    # Apply reaction effects
    effects_applied: list[dict] = []
    damage_dealt = 0

    if reaction_input.reaction_type == "brace":
        # Brace grants resistance to triggering attack
        effects_applied.append({
            "type": "brace",
            "effect": "resistance_to_triggering_attack",
            "duration": "until_start_of_next_turn",
        })
    elif reaction_input.reaction_type == "overwatch":
        # Overwatch allows a skirmish attack
        effects_applied.append({
            "type": "overwatch",
            "effect": "skirmish_attack",
            "targets": reaction_input.target_ids,
        })
        # Actual damage would be resolved by calling combat_helpers

    # Update scenario
    updated_combatants = list(scenario.combatants)
    updated_combatants[reactor_idx] = updated_reactor

    updated_scenario = MechCombatScenario(
        combatants=updated_combatants,
        grapples=list(scenario.grapples),
        rounds=list(scenario.rounds),
        terrain=scenario.terrain,
        environment=scenario.environment,
        deployables=dict(scenario.deployables),
    )

    return updated_scenario, updated_economy, ReactionResult(
        success=True,
        reaction_used=reaction_input.reaction_type,
        effects_applied=effects_applied,
        damage_dealt=damage_dealt,
    )


# =============================================================================
# Available Actions Query
# =============================================================================


def get_available_actions(
    scenario: MechCombatScenario,
    actor_id: str,
    economy: ActionEconomyState,
) -> AvailableActionsResult:
    """Get available actions for an actor given current economy.

    Args:
        scenario: Current combat scenario
        actor_id: ID of the actor to check
        economy: Current action economy state

    Returns:
        AvailableActionsResult with categorized available actions
    """
    # Find the actor
    actor: CombatantState | None = None
    for c in scenario.combatants:
        if c.id == actor_id:
            actor = c
            break

    if actor is None:
        return AvailableActionsResult(
            actor_id=actor_id,
            economy=economy,
            can_overcharge=False,
        )

    # Check economy for each action type
    can_full = economy.full_actions_remaining > 0
    can_quick = economy.quick_actions_remaining > 0
    can_react = economy.reactions_remaining_this_turn > 0
    can_overcharge = economy.can_overcharge

    # Standard full actions
    full_actions: list[AvailableAction] = []
    if can_full:
        full_actions.extend([
            AvailableAction(
                action_id="barrage",
                action_name="Barrage",
                action_type="full",
                is_available=True,
                requires_target=True,
                requires_weapon=True,
            ),
            AvailableAction(
                action_id="full_tech",
                action_name="Full Tech",
                action_type="full",
                is_available=True,
                requires_target=True,
            ),
            AvailableAction(
                action_id="improvised_attack",
                action_name="Improvised Attack",
                action_type="full",
                is_available=True,
                requires_target=True,
            ),
            AvailableAction(
                action_id="stabilize",
                action_name="Stabilize",
                action_type="full",
                is_available=True,
            ),
            AvailableAction(
                action_id="disengage",
                action_name="Disengage",
                action_type="full",
                is_available=True,
            ),
        ])
    else:
        full_actions.extend([
            AvailableAction(
                action_id="barrage",
                action_name="Barrage",
                action_type="full",
                is_available=False,
                unavailable_reason="Full action already used",
                requires_target=True,
                requires_weapon=True,
            ),
        ])

    # Standard quick actions
    quick_actions: list[AvailableAction] = []
    if can_quick:
        quick_actions.extend([
            AvailableAction(
                action_id="skirmish",
                action_name="Skirmish",
                action_type="quick",
                is_available=True,
                requires_target=True,
                requires_weapon=True,
            ),
            AvailableAction(
                action_id="boost",
                action_name="Boost",
                action_type="quick",
                is_available=True,
            ),
            AvailableAction(
                action_id="ram",
                action_name="Ram",
                action_type="quick",
                is_available=True,
                requires_target=True,
            ),
            AvailableAction(
                action_id="grapple",
                action_name="Grapple",
                action_type="quick",
                is_available=True,
                requires_target=True,
            ),
            AvailableAction(
                action_id="quick_tech",
                action_name="Quick Tech",
                action_type="quick",
                is_available=True,
                requires_target=True,
            ),
            AvailableAction(
                action_id="hide",
                action_name="Hide",
                action_type="quick",
                is_available=True,
            ),
            AvailableAction(
                action_id="search",
                action_name="Search",
                action_type="quick",
                is_available=True,
            ),
        ])
    else:
        quick_actions.extend([
            AvailableAction(
                action_id="skirmish",
                action_name="Skirmish",
                action_type="quick",
                is_available=False,
                unavailable_reason="No quick actions remaining",
                requires_target=True,
                requires_weapon=True,
            ),
        ])

    # Free actions (always available)
    free_actions: list[AvailableAction] = [
        AvailableAction(
            action_id="overcharge",
            action_name="Overcharge",
            action_type="free",
            is_available=can_overcharge,
            unavailable_reason=None if can_overcharge else "Already overcharged this turn",
        ),
        AvailableAction(
            action_id="mount_dismount",
            action_name="Mount/Dismount",
            action_type="free",
            is_available=True,
        ),
    ]

    # Reactions
    reactions: list[AvailableAction] = [
        AvailableAction(
            action_id="brace",
            action_name="Brace",
            action_type="reaction",
            is_available=can_react and actor.per_round_reactions.get("brace", 0) < 1,
            unavailable_reason=None if can_react else "No reactions remaining this turn",
        ),
        AvailableAction(
            action_id="overwatch",
            action_name="Overwatch",
            action_type="reaction",
            is_available=can_react and actor.per_round_reactions.get("overwatch", 0) < 1,
            unavailable_reason=None if can_react else "No reactions remaining this turn",
            requires_target=True,
            requires_weapon=True,
        ),
    ]

    # Protocols (at start of turn only - simplified)
    protocols: list[AvailableAction] = []

    return AvailableActionsResult(
        actor_id=actor_id,
        economy=economy,
        full_actions=full_actions,
        quick_actions=quick_actions,
        free_actions=free_actions,
        reactions=reactions,
        protocols=protocols,
        can_overcharge=can_overcharge,
    )


# =============================================================================
# Resource Mutation Helpers
# =============================================================================


def apply_damage(
    scenario: MechCombatScenario,
    target_id: str,
    damage: int,
    armor_piercing: int = 0,
) -> tuple[MechCombatScenario, ResourceChange]:
    """Apply damage to a combatant.

    Args:
        scenario: Current combat scenario
        target_id: ID of the target taking damage
        damage: Amount of damage
        armor_piercing: AP value to bypass armor

    Returns:
        Tuple of (updated scenario, ResourceChange record)
    """
    # Find target
    target: CombatantState | None = None
    target_idx: int = -1
    for i, c in enumerate(scenario.combatants):
        if c.id == target_id:
            target = c
            target_idx = i
            break

    if target is None:
        return scenario, ResourceChange(combatant_id=target_id)

    # Calculate effective damage
    effective_armor = max(0, target.stats.armor - armor_piercing)
    net_damage = max(0, damage - effective_armor)

    # Apply to HP
    new_hp = max(0, target.resources.hp_current - net_damage)
    hp_change = target.resources.hp_current - new_hp

    new_resources = target.resources.model_copy(update={"hp_current": new_hp})
    updated_target = target.model_copy(update={"resources": new_resources})

    updated_combatants = list(scenario.combatants)
    updated_combatants[target_idx] = updated_target

    updated_scenario = MechCombatScenario(
        combatants=updated_combatants,
        grapples=list(scenario.grapples),
        rounds=list(scenario.rounds),
        terrain=scenario.terrain,
        environment=scenario.environment,
        deployables=dict(scenario.deployables),
    )

    return updated_scenario, ResourceChange(
        combatant_id=target_id,
        hp_change=-hp_change,
    )


def apply_heat(
    scenario: MechCombatScenario,
    target_id: str,
    heat: int,
) -> tuple[MechCombatScenario, ResourceChange]:
    """Apply heat to a combatant.

    Args:
        scenario: Current combat scenario
        target_id: ID of the target gaining heat
        heat: Amount of heat

    Returns:
        Tuple of (updated scenario, ResourceChange record)
    """
    # Find target
    target: CombatantState | None = None
    target_idx: int = -1
    for i, c in enumerate(scenario.combatants):
        if c.id == target_id:
            target = c
            target_idx = i
            break

    if target is None:
        return scenario, ResourceChange(combatant_id=target_id)

    # Apply heat (can exceed cap - triggers overheat check)
    new_heat = target.resources.heat_current + heat

    new_resources = target.resources.model_copy(update={"heat_current": new_heat})
    updated_target = target.model_copy(update={"resources": new_resources})

    updated_combatants = list(scenario.combatants)
    updated_combatants[target_idx] = updated_target

    updated_scenario = MechCombatScenario(
        combatants=updated_combatants,
        grapples=list(scenario.grapples),
        rounds=list(scenario.rounds),
        terrain=scenario.terrain,
        environment=scenario.environment,
        deployables=dict(scenario.deployables),
    )

    return updated_scenario, ResourceChange(
        combatant_id=target_id,
        heat_change=heat,
    )


def clear_heat(
    scenario: MechCombatScenario,
    target_id: str,
    amount: int,
) -> tuple[MechCombatScenario, ResourceChange]:
    """Clear heat from a combatant.

    Args:
        scenario: Current combat scenario
        target_id: ID of the target clearing heat
        amount: Amount of heat to clear

    Returns:
        Tuple of (updated scenario, ResourceChange record)
    """
    # Find target
    target: CombatantState | None = None
    target_idx: int = -1
    for i, c in enumerate(scenario.combatants):
        if c.id == target_id:
            target = c
            target_idx = i
            break

    if target is None:
        return scenario, ResourceChange(combatant_id=target_id)

    # Clear heat (minimum 0)
    heat_cleared = min(amount, target.resources.heat_current)
    new_heat = target.resources.heat_current - heat_cleared

    new_resources = target.resources.model_copy(update={"heat_current": new_heat})
    updated_target = target.model_copy(update={"resources": new_resources})

    updated_combatants = list(scenario.combatants)
    updated_combatants[target_idx] = updated_target

    updated_scenario = MechCombatScenario(
        combatants=updated_combatants,
        grapples=list(scenario.grapples),
        rounds=list(scenario.rounds),
        terrain=scenario.terrain,
        environment=scenario.environment,
        deployables=dict(scenario.deployables),
    )

    return updated_scenario, ResourceChange(
        combatant_id=target_id,
        heat_change=-heat_cleared,
    )


# =============================================================================
# Private Helpers
# =============================================================================


def _get_basic_available_actions(actor: CombatantState) -> list[str]:
    """Get basic list of available action IDs for an actor.

    This is a simplified version - a full implementation would check
    weapons, systems, statuses, cooldowns, etc.
    """
    actions = [
        # Full actions
        "barrage",
        "full_tech",
        "improvised_attack",
        "stabilize",
        "disengage",
        # Quick actions
        "skirmish",
        "boost",
        "ram",
        "grapple",
        "quick_tech",
        "hide",
        "search",
        # Free actions
        "overcharge",
        "mount_dismount",
        # Reactions
        "brace",
        "overwatch",
    ]

    # Filter based on status conditions
    if "stunned" in actor.statuses:
        # Stunned: cannot take actions except mount/dismount/eject
        actions = ["mount_dismount"]
    elif "jammed" in actor.statuses:
        # Jammed: only improvised attacks and grapples
        actions = [a for a in actions if a in ["improvised_attack", "grapple", "mount_dismount", "brace"]]

    return actions
